mysql:
  database: ${MARIADB_DATABASE}
  user: ${MARIADB_USER}
  password: ${MARIADB_SMARTDOOR_PASSWORD}
  host: ${MARIADB_HOST}
  port: ${MARIADB_PORT}
  raise_on_warnings: false

bluetooth:
  # How long the Bluetooth service should search for devices. Given in seconds.
  discover_duration: 10
  # The interval in which the scan method will be called. Given in seconds.
  scan_interval: 20
